=== dusan233/ist2020/oglasi.dtd
<!ELEMENT Oglasi (Oglas)+>
<!ELEMENT Oglas (KategorijaOglasa,DatumIsteka,Cena,TekstOglasa,Oznaka+,EmailProdavca+)>
<!ELEMENT KategorijaOglasa (#PCDATA)>
<!ELEMENT DatumIsteka (#PCDATA)>
<!ELEMENT Cena (#PCDATA)>
<!ATTLIST Cena valuta CDATA "dinar">
<!ELEMENT TekstOglasa (#PCDATA) >
<!ELEMENT Oznaka ANY>
<!ELEMENT EmailProdavca (#PCDATA)>
<!ATTLIST EmailProdavca tip (privatni|sluzbeni) #REQUIRED>

=== dusan233/ist2020/oglasi.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Oglasi SYSTEM "oglasi.dtd">
<Oglasi xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.w3schools.com oglasi.xsd">>
<Oglas>
  <KategorijaOglasa>automobili</KategorijaOglasa>
  <DatumIsteka>
    2020-08-23
  </DatumIsteka>
  <Cena valuta="dinar">500000</Cena>
  <TekstOglasa>
    VW Golf Plus Auto u odličnom stanju. Održavan i kupljen u Švajcarskoj.
    Najbolja verzija benzin VW 1.6 motora. Potpuno zdrav i očuvan, bez nekog ulaganja. Limarski ne udaran i nije lupan.
  </TekstOglasa>
  <Oznaka>Volkswagen</Oznaka>
  <EmailProdavca tip="sluzbeni">djura12@gmail.com</EmailProdavca>
</Oglas>
</Oglasi>
